### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by arunsahoo-xt**
Added a banner ,new background  and edited chef cards

### CODE REVIEW

**Comment by Aakarsh05** [comment]
Please host the website that you made and then send it to me.

**Comment by arunsahoo-xt** [comment]
https://arunsahoo-xt.github.io/MumbaiChefs/

**Comment by arunsahoo-xt** [comment]
> Please host the website that you made and then send it to me.

I commented the link

**Comment by Aakarsh05** [comment]
Some people who told me that they will be giving their PRs has not given yet. If they do not send it by today I will merge the code

**Comment by arunsahoo-xt** [comment]
> Some people who told me that they will be giving their PRs has not given yet. If they do not send it by today I will merge the code
Okay

**Comment by arunsahoo-xt** [comment]
> Some people who told me that they will be giving their PRs has not given yet. If they do not send it by today I will merge the code

Did u liked the changes?

**Comment by Aakarsh05** [comment]
The changes where fine. If I did'nt receive anything better than this I will merge it.

**Comment by arunsahoo-xt** [comment]
> The changes where fine. If I did'nt receive anything better than this I will merge it.

I think it is better because I added a welcome banner to tell the visitors what this is about .No point in directly showing the visitors the chef list without context and also the site is fully responsive.

**Pull request merged**
